language: objective-c
osx_image: xcode10.2

before_install:
   - gem install cocoapods --no-document --quiet

script:
   - xcodebuild test -project Gloss.xcodeproj -scheme GlossTests -destination 'platform=iOS Simulator,name=iPhone 6,OS=12.0'
   - pod lib lint --quick
